local application = require("test.application")

describe("test ivr", function()
    local app = application()
    it("answers the phone", function()
        app.should.channel.answer()
        app.should.channel.say("This is an example application. Enter any number followed by the pound sign.")
    end)
    it("asks for numbers", function()
        app.should.channel.gather("234")
    end)
    it("repeats the numbers", function()
        app.should.channel.say("234")
    end)
    it("hangs up", function()
        app.should.channel.hangup()
    end)
end)

